[project]
name = "form2chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.47.0",
    "markdownify>=1.2.0",
    "playwright>=1.55.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
